# Generated by Django 4.2.23 on 2025-07-10 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OasisTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('assessment_type', models.CharField(choices=[('SOC', 'Start of Care'), ('ROC', 'Resumption of Care'), ('RECERT', 'Recertification'), ('FU', 'Other Follow-up'), ('TRANSFER', 'Transfer'), ('DC', 'Discharge')], max_length=10)),
                ('discipline', models.CharField(choices=[('SN', 'Skilled Nursing'), ('PT', 'Physical Therapy'), ('OT', 'Occupational Therapy'), ('ST', 'Speech Therapy'), ('MSW', 'Medical Social Work')], max_length=5)),
                ('template_structure', models.JSONField()),
                ('version', models.CharField(default='E', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OasisAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('SOC', 'Start of Care'), ('ROC', 'Resumption of Care'), ('RECERT', 'Recertification'), ('FU', 'Other Follow-up'), ('TRANSFER', 'Transfer'), ('DC', 'Discharge')], max_length=10)),
                ('assessment_date', models.DateField()),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('race_ethnicity', models.JSONField(blank=True, default=dict)),
                ('prior_functioning_adl', models.JSONField(blank=True, default=dict)),
                ('prior_functioning_iadl', models.JSONField(blank=True, default=dict)),
                ('primary_diagnosis', models.CharField(max_length=200)),
                ('other_diagnoses', models.JSONField(blank=True, default=list)),
                ('grooming', models.IntegerField(blank=True, choices=[(0, 'Able'), (1, 'Supervision'), (2, 'Assistance'), (3, 'Unable')], null=True)),
                ('dressing_upper', models.IntegerField(blank=True, choices=[(0, 'Able'), (1, 'Supervision'), (2, 'Assistance'), (3, 'Unable')], null=True)),
                ('dressing_lower', models.IntegerField(blank=True, choices=[(0, 'Able'), (1, 'Supervision'), (2, 'Assistance'), (3, 'Unable')], null=True)),
                ('bathing', models.IntegerField(blank=True, choices=[(0, 'Able'), (1, 'Supervision'), (2, 'Assistance'), (3, 'Unable')], null=True)),
                ('toileting', models.IntegerField(blank=True, choices=[(0, 'Able'), (1, 'Supervision'), (2, 'Assistance'), (3, 'Unable')], null=True)),
                ('transferring', models.IntegerField(blank=True, choices=[(0, 'Able'), (1, 'Supervision'), (2, 'Assistance'), (3, 'Unable')], null=True)),
                ('ambulation', models.IntegerField(blank=True, choices=[(0, 'Able'), (1, 'Supervision'), (2, 'Assistance'), (3, 'Unable')], null=True)),
                ('feeding', models.IntegerField(blank=True, choices=[(0, 'Able'), (1, 'Supervision'), (2, 'Assistance'), (3, 'Unable')], null=True)),
                ('cognitive_functioning', models.IntegerField(blank=True, choices=[(0, 'Alert/oriented'), (1, 'Requires prompting'), (2, 'Requires assistance'), (3, 'Requires considerable assistance'), (4, 'Unable to care')], null=True)),
                ('vision', models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Partially impaired'), (2, 'Severely impaired')], null=True)),
                ('hearing', models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'Minimal difficulty'), (2, 'Moderate difficulty'), (3, 'Severe difficulty')], null=True)),
                ('complete_data', models.JSONField(blank=True, default=dict)),
                ('ai_insights', models.JSONField(blank=True, default=dict)),
                ('risk_scores', models.JSONField(blank=True, default=dict)),
                ('is_completed', models.BooleanField(default=False)),
                ('submitted_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oasis_assessments', to='patients.patient')),
            ],
            options={
                'ordering': ['-assessment_date'],
            },
        ),
    ]
